/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifikasiRouteImport } from './routes/verifikasi'
import { Route as RiwayatRouteImport } from './routes/riwayat'
import { Route as PreprocessingRouteImport } from './routes/preprocessing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRiwayatRouteImport } from './routes/admin.riwayat'

const VerifikasiRoute = VerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const RiwayatRoute = RiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => rootRouteImport,
} as any)
const PreprocessingRoute = PreprocessingRouteImport.update({
  id: '/preprocessing',
  path: '/preprocessing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiwayatRoute = AdminRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/preprocessing': typeof PreprocessingRoute
  '/riwayat': typeof RiwayatRoute
  '/verifikasi': typeof VerifikasiRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/preprocessing': typeof PreprocessingRoute
  '/riwayat': typeof RiwayatRoute
  '/verifikasi': typeof VerifikasiRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/preprocessing': typeof PreprocessingRoute
  '/riwayat': typeof RiwayatRoute
  '/verifikasi': typeof VerifikasiRoute
  '/admin/riwayat': typeof AdminRiwayatRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/preprocessing'
    | '/riwayat'
    | '/verifikasi'
    | '/admin/riwayat'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/preprocessing'
    | '/riwayat'
    | '/verifikasi'
    | '/admin/riwayat'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/preprocessing'
    | '/riwayat'
    | '/verifikasi'
    | '/admin/riwayat'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PreprocessingRoute: typeof PreprocessingRoute
  RiwayatRoute: typeof RiwayatRoute
  VerifikasiRoute: typeof VerifikasiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verifikasi': {
      id: '/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof VerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/riwayat': {
      id: '/riwayat'
      path: '/riwayat'
      fullPath: '/riwayat'
      preLoaderRoute: typeof RiwayatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preprocessing': {
      id: '/preprocessing'
      path: '/preprocessing'
      fullPath: '/preprocessing'
      preLoaderRoute: typeof PreprocessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/riwayat': {
      id: '/admin/riwayat'
      path: '/riwayat'
      fullPath: '/admin/riwayat'
      preLoaderRoute: typeof AdminRiwayatRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminRiwayatRoute: typeof AdminRiwayatRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminRiwayatRoute: AdminRiwayatRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PreprocessingRoute: PreprocessingRoute,
  RiwayatRoute: RiwayatRoute,
  VerifikasiRoute: VerifikasiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
